### ISSUE TITLE
Jestの導入

### ISSUE THREAD

**Issue by hatsu38** [hatsu38/tech-tv#59]
## 📝 概要

Jestを導入したいです

## 💪 実現したいこと・ユーザーストーリー

Jestを導入して、確認のためにも簡単なテストを1つだけでも書いていただけると

## 🆗 受け入れ基準

- Jestが導入されていること
- Jestのテストがあること
- CircleCIでJestが動いているとなおよし(相談してください)

## 📎 資料

https://jestjs.io/

**Comment by fujjima** [comment]
I'll do it🐧
