### ISSUE TITLE
rubyを2.7.2にversion upする

### ISSUE THREAD

**Issue by hatsu38** [hatsu38/tech-tv#62]
## 📝 概要

rubyを2.7.2にversion upする

## 💪 実現したいこと・ユーザーストーリー

- Rubyを2.7.2にversion upする
- rubocopで指定しているバージョンも2.7.2にする
- CircleCIのRubyのバージョンも2.7.2にする
- Rubyの2.7系のとき、Bundlerのバージョンも2.1.4にあげる必要がある(かも?と思います。ちなみにCIでもBundlerのバージョン指定しています)

## 🆗 受け入れ基準

- Rubyを2.7.2にversion upしてAppが動くこと
- Rubocopが2.7.2のスタイルで動くこと
- CIが2.7.2で動くこと

## 📎 資料

Ruby 2.6からの変更点
https://www.ruby-lang.org/ja/news/2019/12/25/ruby-2-7-0-released/

**Comment by fujjima** [comment]
@hatsu38 
言い忘れてた、私がやるのでアサインお願いしやす🐧
